[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200

[[redirects]]
  from = "/Public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
