// src/World/Agents/AgentState.js

// Énumération des états possibles pour un agent
export default {
    IDLE: 'IDLE',
    AT_HOME: 'AT_HOME',
    AT_WORK: 'AT_WORK',
    PREPARING_FOR_WORK: 'PREPARING_FOR_WORK',
    READY_TO_LEAVE_FOR_WORK: 'READY_TO_LEAVE_FOR_WORK',
    IN_TRANSIT_TO_WORK: 'IN_TRANSIT_TO_WORK',
    DRIVING_TO_WORK: 'DRIVING_TO_WORK',
    PREPARING_FOR_HOME: 'PREPARING_FOR_HOME',
    READY_TO_LEAVE_FOR_HOME: 'READY_TO_LEAVE_FOR_HOME',
    IN_TRANSIT_TO_HOME: 'IN_TRANSIT_TO_HOME',
    DRIVING_HOME: 'DRIVING_HOME',
    WAITING_FOR_PATH: 'WAITING_FOR_PATH',
    REQUESTING_PATH_FOR_WORK: 'REQUESTING_PATH_FOR_WORK',
    REQUESTING_PATH_FOR_HOME: 'REQUESTING_PATH_FOR_HOME',
    REQUESTING_PATH_FOR_COMMERCIAL: 'REQUESTING_PATH_FOR_COMMERCIAL',
    IN_TRANSIT_TO_COMMERCIAL: 'IN_TRANSIT_TO_COMMERCIAL',
    READY_TO_LEAVE_FOR_COMMERCIAL: 'READY_TO_LEAVE_FOR_COMMERCIAL',
    AT_COMMERCIAL: 'AT_COMMERCIAL',
    
    // États pour le comportement week-end
    WEEKEND_WALK_PREPARING: 'WEEKEND_WALK_PREPARING',
    WEEKEND_WALK_REQUESTING_PATH: 'WEEKEND_WALK_REQUESTING_PATH',
    WEEKEND_WALK_READY: 'WEEKEND_WALK_READY',
    WEEKEND_WALKING: 'WEEKEND_WALKING',
    WEEKEND_WALK_RETURNING_TO_SIDEWALK: 'WEEKEND_WALK_RETURNING_TO_SIDEWALK'
};